In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
#Cargando data del 1 al 5 de Abril
abril_01_df = pd.read_csv('validacionTroncal20230401.csv') #Cargando data Primero de Abril 
abril_02_df = pd.read_csv('validacionTroncal20230402.csv')
abril_03_df = pd.read_csv('validacionTroncal20230403.csv')
abril_04_df = pd.read_csv('validacionTroncal20230404.csv')
abril_05_df = pd.read_csv('validacionTroncal20230405.csv')

In [28]:
#Concatenando data 
transmi_df=pd.concat([abril_01_df,abril_02_df,abril_03_df, abril_04_df, abril_05_df])
transmi_df

,Acceso_Estacion,Day_Group_Type,Dispositivo,Emisor,Estacion_Parada,Fase,Fecha_Clearing,Fecha_Transaccion,Hora_Pico_SN,ID_Vehiculo,...,Numero_Tarjeta,Operador,Ruta,Saldo_Despues_Transaccion,Saldo_Previo_a_Transaccion,Sistema,Tipo_Tarifa,Tipo_Tarjeta,Tipo_Vehiculo,Valor
0,(23) Acceso Peatonal,Dia 1,10000923,(3101000) Bogota Card(Citizen),(05000) Portal Américas,Fase 3,2023-04-01,2023-04-01 03:50:08,Peak Time,NaN,...,ae7bc213c6ec40815bbd10c8f7f9aef465546c72eaf839...,(201) Trunk agency,NaN,2200.0,5150.0,TRONCAL,1,tullave Plus,NaN,2950.0
1,(23) Acceso Peatonal,Dia 1,10000920,(3101000) Bogota Card(Citizen),(05000) Portal Américas,Fase 3,2023-04-01,2023-04-01 03:50:09,Peak Time,NaN,...,cc31a01d33204e8c48fd46eff78d44db1b5ab5c9385d35...,(201) Trunk agency,NaN,14850.0,17800.0,TRONCAL,1,tullave Plus,NaN,2950.0
2,(23) Acceso Peatonal,Dia 1,10000921,(3101000) Bogota Card(Citizen),(05000) Portal Américas,Fase 3,2023-04-01,2023-04-01 03:50:09,Peak Time,NaN,...,90f135a0d4d61b27d49e13cfcb2a1ad6404fed3c1a8b72...,(201) Trunk agency,NaN,83000.0,85950.0,TRONCAL,1,tullave Plus,NaN,2950.0
3,(23) Acceso Peatonal,Dia 1,10001259,(3101000) Bogota Card(Citizen),(05000) Portal Américas,Fase 3,2023-04-01,2023-04-01 03:50:09,Peak Time,NaN,...,c9060006a1c524bbf567a07ba16e5ee05462d538ab8045...,(201) Trunk agency,NaN,12000.0,14950.0,TRONCAL,1,tullave Plus,NaN,2950.0
4,(23) Acceso Peatonal,Dia 1,10000919,(3101000) Bogota Card(Citizen),(05000) Portal Américas,Fase 3,2023-04-01,2023-04-01 03:50:10,Peak Time,NaN,...,c5542d82409375936da7cd166004e9d61a5f05bbe7da10...,(201) Trunk agency,NaN,12750.0,15700.0,TRONCAL,1,tullave Plus,NaN,2950.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421410,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,10000591,(3101000) Bogota Card(Citizen),(08000) Portal Tunal,Fase 3,2023-04-05,2023-04-06 03:48:41,Peak Time,NaN,...,b05295a777a2d72ca3bf4ea022d0ef20399caae17a46b5...,(201) Trunk agency,NaN,1400.0,4350.0,TRONCAL,1,tullave Básica,NaN,2950.0
1421411,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,10000589,(3101000) Bogota Card(Citizen),(08000) Portal Tunal,Fase 3,2023-04-05,2023-04-06 03:48:51,Peak Time,NaN,...,e4630cc30cff4328387f300b421b1b271854de4a623f27...,(201) Trunk agency,NaN,8600.0,8800.0,TRONCAL,1,tullave Plus,NaN,200.0
1421412,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,10000589,(3101000) Bogota Card(Citizen),(08000) Portal Tunal,Fase 3,2023-04-05,2023-04-06 03:48:54,Peak Time,NaN,...,dc5cbf613532b8f79aeb9e8bb65c2ebd16930e064dae24...,(201) Trunk agency,NaN,19900.0,20100.0,TRONCAL,1,tullave Plus,NaN,200.0
1421413,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,10000589,(3101000) Bogota Card(Citizen),(08000) Portal Tunal,Fase 3,2023-04-05,2023-04-06 03:49:19,Peak Time,NaN,...,188a142fc113cf1b5ce6f11fe94139967be2f6cacb3934...,(201) Trunk agency,NaN,3900.0,6850.0,TRONCAL,1,tullave Plus,NaN,2950.0
1421414,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,10000589,(3101000) Bogota Card(Citizen),(08000) Portal Tunal,Fase 3,2023-04-05,2023-04-06 03:49:24,Peak Time,NaN,...,a61f2abad63726c0c6d7600161daf013bb1834fe056eaa...,(201) Trunk agency,NaN,6600.0,9550.0,TRONCAL,1,tullave Plus,NaN,2950.0

In [29]:
transmi_df.dtypes

Acceso_Estacion                object
Day_Group_Type                 object
Dispositivo                     int64
Emisor                         object
Estacion_Parada                object
Fase                           object
Fecha_Clearing                 object
Fecha_Transaccion              object
Hora_Pico_SN                   object
ID_Vehiculo                   float64
Linea                          object
Nombre_Perfil                  object
Numero_Tarjeta                 object
Operador                       object
Ruta                          float64
Saldo_Despues_Transaccion     float64
Saldo_Previo_a_Transaccion    float64
Sistema                        object
Tipo_Tarifa                     int64
Tipo_Tarjeta                   object
Tipo_Vehiculo                 float64
Valor                         float64
dtype: object

In [30]:
#SELECCIÓN DE COLUMNAS CORRELACIONADAS
transmi_df = transmi_df[['Acceso_Estacion',
 'Day_Group_Type',
 'Estacion_Parada',
 'Fecha_Clearing',
 'Fecha_Transaccion',
 'Linea',
 'Nombre_Perfil',
 'Tipo_Tarjeta',
 'Valor'
]]
#method=bfill
#aeropuertos_df=aeropuertos_df.fillna() 
transmi_df.tail()

,Acceso_Estacion,Day_Group_Type,Estacion_Parada,Fecha_Clearing,Fecha_Transaccion,Linea,Nombre_Perfil,Tipo_Tarjeta,Valor
1421410,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:41,(34) Zona H Caracas Sur,(001) Anonymous,tullave Básica,2950.0
1421411,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:51,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,200.0
1421412,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:54,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,200.0
1421413,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:49:19,(34) Zona H Caracas Sur,(009) Apoyo Ciudadano Reexpedición,tullave Plus,2950.0
1421414,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:49:24,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,2950.0

In [31]:
#CAMBIANDO NaN POR 0 
transmi_df=transmi_df.fillna(0) 
transmi_df.tail()

,Acceso_Estacion,Day_Group_Type,Estacion_Parada,Fecha_Clearing,Fecha_Transaccion,Linea,Nombre_Perfil,Tipo_Tarjeta,Valor
1421410,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:41,(34) Zona H Caracas Sur,(001) Anonymous,tullave Básica,2950.0
1421411,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:51,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,200.0
1421412,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:54,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,200.0
1421413,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:49:19,(34) Zona H Caracas Sur,(009) Apoyo Ciudadano Reexpedición,tullave Plus,2950.0
1421414,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:49:24,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,2950.0

In [32]:
#Agregando fila con día del mes 

transmi_df['Dia']=transmi_df['Fecha_Clearing'].str.slice(9, 10)
transmi_df

,Acceso_Estacion,Day_Group_Type,Estacion_Parada,Fecha_Clearing,Fecha_Transaccion,Linea,Nombre_Perfil,Tipo_Tarjeta,Valor,Dia
0,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:08,(31) Zona F Av. Américas,(001) Adulto,tullave Plus,2950.0,1
1,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:09,(31) Zona F Av. Américas,(006) Apoyo Ciudadano,tullave Plus,2950.0,1
2,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:09,(31) Zona F Av. Américas,(001) Adulto,tullave Plus,2950.0,1
3,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:09,(31) Zona F Av. Américas,(001) Adulto,tullave Plus,2950.0,1
4,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:10,(31) Zona F Av. Américas,(001) Adulto,tullave Plus,2950.0,1
...,...,...,...,...,...,...,...,...,...,...
1421410,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:41,(34) Zona H Caracas Sur,(001) Anonymous,tullave Básica,2950.0,5
1421411,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:51,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,200.0,5
1421412,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:54,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,200.0,5
1421413,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:49:19,(34) Zona H Caracas Sur,(009) Apoyo Ciudadano Reexpedición,tullave Plus,2950.0,5
1421414,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:49:24,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,2950.0,5

In [33]:
#Agregando fila con hora de transacción 

transmi_df['Hora']=transmi_df['Fecha_Transaccion'].str.slice(11, 13)
transmi_df

,Acceso_Estacion,Day_Group_Type,Estacion_Parada,Fecha_Clearing,Fecha_Transaccion,Linea,Nombre_Perfil,Tipo_Tarjeta,Valor,Dia,Hora
0,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:08,(31) Zona F Av. Américas,(001) Adulto,tullave Plus,2950.0,1,03
1,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:09,(31) Zona F Av. Américas,(006) Apoyo Ciudadano,tullave Plus,2950.0,1,03
2,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:09,(31) Zona F Av. Américas,(001) Adulto,tullave Plus,2950.0,1,03
3,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:09,(31) Zona F Av. Américas,(001) Adulto,tullave Plus,2950.0,1,03
4,(23) Acceso Peatonal,Dia 1,(05000) Portal Américas,2023-04-01,2023-04-01 03:50:10,(31) Zona F Av. Américas,(001) Adulto,tullave Plus,2950.0,1,03
...,...,...,...,...,...,...,...,...,...,...,...
1421410,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:41,(34) Zona H Caracas Sur,(001) Anonymous,tullave Básica,2950.0,5,03
1421411,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:51,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,200.0,5,03
1421412,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:48:54,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,200.0,5,03
1421413,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:49:19,(34) Zona H Caracas Sur,(009) Apoyo Ciudadano Reexpedición,tullave Plus,2950.0,5,03
1421414,(KD) DESALIMENTACIÓN - SAN JOAQUÍN /JJ RONDÓN ...,Dia 3,(08000) Portal Tunal,2023-04-05,2023-04-06 03:49:24,(34) Zona H Caracas Sur,(001) Adulto,tullave Plus,2950.0,5,03

In [34]:
#Descargando Data para trabajar desde PowerBi la visualización
transmi_df.to_csv('Data_transmilenio.csv', index=False)

## RESUMEN MESES DESDE OCTUBRE A DICIEMBRE 2022 Y ENERO A ABRIL 2023

In [73]:
resumen_oct22 = pd.read_excel('Resumen_oct.xlsx')
resumen_nov22 = pd.read_excel('Resumen_nov.xlsx')
resumen_dic22 = pd.read_excel('Resumen_dic.xlsx')

resumen_ene23 = pd.read_excel('Resumen_enero.xlsx')
resumen_feb23 = pd.read_excel('Resumen_feb.xlsx')
resumen_mar23 = pd.read_excel('Resumen_mar.xlsx')
resumen_abr23 = pd.read_excel('Resumen_abril.xlsx')



#Concatenando data 
resumen_meses=pd.concat([resumen_oct22,resumen_nov22,resumen_dic22, resumen_ene23, resumen_feb23,resumen_mar23,resumen_abr23])
resumen_meses

,Fase,Mes,Línea,Estación,Acceso de Estación,Intervalo,1,2,3,4,...,23,24,25,26,27,28,29,30,31,Total general
0,Fase 3,Octubre,(11) Zona K Calle 26,(06000) Portal Eldorado,(01) PLAT2 ALIM-DESAL FONTIBÓN/FONTIBÓN CENTRO...,00:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,Fase 3,Octubre,(11) Zona K Calle 26,(06000) Portal Eldorado,(01) PLAT2 ALIM-DESAL FONTIBÓN/FONTIBÓN CENTRO...,04:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,Fase 3,Octubre,(11) Zona K Calle 26,(06000) Portal Eldorado,(01) PLAT2 ALIM-DESAL FONTIBÓN/FONTIBÓN CENTRO...,04:15:00,16.0,4.0,25.0,29.0,...,2.0,19.0,18.0,31.0,24.0,18.0,7.0,5.0,17.0,573
3,Fase 3,Octubre,(11) Zona K Calle 26,(06000) Portal Eldorado,(01) PLAT2 ALIM-DESAL FONTIBÓN/FONTIBÓN CENTRO...,04:30:00,31.0,8.0,82.0,56.0,...,5.0,46.0,41.0,42.0,51.0,33.0,45.0,8.0,54.0,1189
4,Fase 3,Octubre,(11) Zona K Calle 26,(06000) Portal Eldorado,(01) PLAT2 ALIM-DESAL FONTIBÓN/FONTIBÓN CENTRO...,04:45:00,58.0,15.0,66.0,99.0,...,21.0,103.0,97.0,116.0,86.0,97.0,45.0,21.0,104.0,2484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
64951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
64952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
64953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
64954,Total general,NaN,Total general,Total general,Total general,Total general,1253387.0,544931.0,1618174.0,1570281.0,...,569808.0,1975283.0,2016334.0,2023797.0,2020864.0,1966548.0,1308239.0,605378.0,NaN,43678458

In [74]:
#CAMBIANDO NaN POR 0 
resumen_meses=resumen_meses.fillna(0) 
resumen_meses.tail()

,Fase,Mes,Línea,Estación,Acceso de Estación,Intervalo,1,2,3,4,...,23,24,25,26,27,28,29,30,31,Total general
64950,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
64951,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
64952,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
64953,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
64954,Total general,0,Total general,Total general,Total general,Total general,1253387.0,544931.0,1618174.0,1570281.0,...,569808.0,1975283.0,2016334.0,2023797.0,2020864.0,1966548.0,1308239.0,605378.0,0.0,43678458

In [75]:
resumen_meses = resumen_meses.drop(resumen_meses[resumen_meses['Acceso de Estación']=='(0) (Unknown)'].index) #Quitando datos de acceso a estación desconocidos

In [76]:
resumen_meses = resumen_meses.drop(resumen_meses[resumen_meses['Línea']=='(1)'].index) #Quitando datos de acceso a estación desconocidos

In [77]:
resumen_meses = resumen_meses.drop(resumen_meses[resumen_meses['Acceso de Estación']=='Total general'].index) #Quitando datos de acceso a estación desconocidos

In [78]:
resumen_meses = resumen_meses.drop(resumen_meses[resumen_meses['Acceso de Estación']==0].index) #Quitando datos de acceso a estación desconocidos

In [79]:
resumen_meses.tail()

,Fase,Mes,Línea,Estación,Acceso de Estación,Intervalo,1,2,3,4,...,23,24,25,26,27,28,29,30,31,Total general
47376,Fase 1,Abril,(39) Zona F Calle 13,(12003) Ricaurte,(01) BATERIA UNO VAGON ORIENTE RICAURTE,09:30:00,20.0,11.0,29.0,27.0,...,4.0,36.0,29.0,25.0,24.0,35.0,21.0,6.0,0.0,672
47377,Fase 1,Abril,(39) Zona F Calle 13,(12003) Ricaurte,(01) BATERIA UNO VAGON ORIENTE RICAURTE,09:45:00,31.0,7.0,39.0,25.0,...,4.0,38.0,29.0,30.0,33.0,34.0,19.0,8.0,0.0,771
47378,Fase 1,Abril,(39) Zona F Calle 13,(12003) Ricaurte,(01) BATERIA UNO VAGON ORIENTE RICAURTE,10:00:00,30.0,6.0,36.0,29.0,...,9.0,34.0,38.0,22.0,31.0,34.0,36.0,7.0,0.0,758
47379,Fase 1,Abril,(39) Zona F Calle 13,(12003) Ricaurte,(01) BATERIA UNO VAGON ORIENTE RICAURTE,10:15:00,35.0,16.0,41.0,38.0,...,9.0,25.0,30.0,42.0,40.0,47.0,44.0,2.0,0.0,895
47380,Fase 1,Abril,(39) Zona F Calle 13,(12003) Ricaurte,(01) BATERIA UNO VAGON ORIENTE RICAURTE,10:30:00,30.0,11.0,40.0,46.0,...,6.0,34.0,40.0,39.0,29.0,43.0,38.0,17.0,0.0,920

In [80]:
#Descargando Data para trabajar desde PowerBi la visualización
resumen_meses.to_csv('Data_7_meses.csv', index=False)